export { default as Sniffer1 } from "./sniffer1.webp";
export { default as Sniffer2 } from "./sniffer2.webp";
export { default as Sniffer3 } from "./sniffer3.webp";
export { default as Sniffer4 } from "./sniffer4.webp";
export { default as Sniffer5 } from "./sniffer5.webp";
export { default as Sniffer6 } from "./sniffer6.webp";
export { default as Sniffer7 } from "./sniffer7.webp";
export { default as Sniffer8 } from "./sniffer8.webp";
export { default as Sniffer9 } from "./sniffer9.webp";
