export { default as Netsafe1 } from "./Netsafe1.png";
export { default as Netsafe2 } from "./Netsafe2.png";
export { default as Netsafe3 } from "./Netsafe3.png";
export { default as Netsafe4 } from "./Netsafe4.png";
export { default as Netsafe5 } from "./Netsafe5.png";
export { default as Netsafe6 } from "./Netsafe6.png";
export { default as Netsafe7 } from "./Netsafe7.png";
export { default as Netsafe8 } from "./Netsafe8.png";
export { default as Netsafe9 } from "./Netsafe9.png";
